version: "3.4"

networks:
  app-network:
    driver: bridge

services:
    nopcommerce_web:
        build: .
        container_name: nopcommerce
        restart: always
        depends_on:
            - cache
            - nopcommerce_database
        ports:
            - "8080:80"
            - "443:443"
        environment:
        #https://learn.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-7.0
        #droplet password UU9H#v141pyq
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/servercert.pfx
        volumes:
            #- ${USERPROFILE}/.aspnet/https:/https/:ro
            #- ${USERPROFILE}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ~/NopCommerce_App_Data:/https/:ro
            - ~/NopCommerce_App_Data:/app/App_Data
        networks:
          - app-network

    cache:
      image: redis:6.2-alpine
      restart: always
      ports:
        - "6379:6379"
      command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      volumes:
        - cache:/data
      networks:
        - app-network
        
    nopcommerce_database:
        image: "mysql:latest"
        networks:
          - app-network
        ports:
            - "3306:3306"
        container_name: nopcommerce_mysql_server
        command: "--default-authentication-plugin=mysql_native_password"
        command: "--lower_case_table_names=1"
        restart: "always"
        environment:
          MYSQL_ROOT_PASSWORD: "g675E*ABPw!8"
        volumes:
            - ~/NopCommerce_App_Data/mysql:/var/lib/mysql
        

volumes:
  cache:
    driver: local

