version: "3.4"

networks:
  app-network:
    driver: bridge

services:
    

    cache:
      image: redis:6.2-alpine
      restart: always
      ports:
        - "6379:6379"
      command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      volumes:
        - cache:/data
      networks:
        - app-network
        
    nopcommerce_database:
        image: "mysql:latest"
        networks:
          - app-network
        ports:
            - "3306:3306"
        container_name: nopcommerce_mysql_server
        command: "--default-authentication-plugin=mysql_native_password"
        command: "--lower_case_table_names=1"
        restart: "always"
        environment:
          MYSQL_ROOT_PASSWORD: "g675E*ABPw!8"
        volumes:
            - ~/NopCommerce_App_Data/mysql:/var/lib/mysql
        

volumes:
  cache:
    driver: local

